# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
before_install:
  - sudo apt-get update
  - sudo apt-get -y install mvn
install: travis_wait mvn install

r:
 - release
os:
 - linux
 - osx
