# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
 - env
 - sudo apt-get -y install python3
r:
 - release
os:
 - linux
 - osx
