# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
 - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then brew install python3           ; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y python3; fi
r:
 - release
os:
 - linux
 - osx
